--local capabilities = vim.lsp.protocol.make_client_capabilities()
--capabilities.textDocument.foldingRange = {
    --dynamicRegistration = false,
    --lineFoldingOnly = true
--}
--
--vim.o.foldcolumn = '1' -- '0' is not bad
--vim.o.foldlevel = 99 -- Using ufo provider need a large value, feel free to decrease the value
--vim.o.foldlevelstart = -1
--vim.o.foldenable = true

--require('ufo').setup()
