#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#26F0F1"
bspc config normal_border_color "#202A25"

bspc rule -a Slack desktop='^5' follow=off
bspc rule -a Firefox desktop='^4' focus=on follow=off
bspc rule -a URxvt:irssi desktop='^6' follow=off
urxvt -name "irssi" -hold -e irssi &
exec slack
exec Firefox
